# TODO: use Clang instead of MSVC
name: CI

on: [ push, pull_request ]

jobs:
  ci:
    strategy:
      matrix:
        release-type: [Debug, Release, RelWithDebInfo, MinSizeRel]
    runs-on: [ windows-latest ]
    name: CI
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=${{ matrix.release-type }} -D OPTIMIZE=YES -S. -Bbuild -G Ninja

      - name: Build 64bit ${{ matrix.release-type }} DLL
        run: cmake --build ./build --config ${{ matrix.release-type }} --target YimMenuV2 --

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/YimMenuV2.dll")) {throw 1}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.release-type }}
          path: build/YimMenuV2.dll
